#!/usr/bin/env python3
"""KomaSCAD command-line tool: list, build, preview and export shogi pieces.

Python 3.8+; standard library only. Preview and export need OpenSCAD 2021.01+
on PATH. Run with --help, or <command> --help, for usage and examples.

Sources (edit these):
    presets/pieces/_defaults.json   settings every piece shares
    presets/pieces/<piece>.json     one file per piece
    presets/games.json              which pieces, and how many, make up each game

Generated by the build command (do not edit):
    presets/games/<game>.json       one Customizer file per game
    shogi_piece.json                every game, for the Customizer
"""

import argparse
import difflib
import functools
import hashlib
import html
import json
import math
import os
import re
import shutil
import struct
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET
import zipfile
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path


VERSION = "3.4"

ROOT = Path(__file__).resolve().parent
SCAD = ROOT / "shogi_piece.scad"
CUSTOMIZER = ROOT / "shogi_piece.json"
PIECES = ROOT / "presets" / "pieces"
RECIPES = ROOT / "presets" / "games.json"
GAMES = ROOT / "presets" / "games"

MODEL_NAMESPACE = "http://schemas.microsoft.com/3dmanufacturing/core/2015/02"
MATERIAL_NAMESPACE = "http://schemas.microsoft.com/3dmanufacturing/material/2015/02"
ET.register_namespace("", MODEL_NAMESPACE)
ET.register_namespace("m", MATERIAL_NAMESPACE)

CONTENT_TYPES = b'''<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/><Default Extension="json" ContentType="application/json"/></Types>'''
RELATIONSHIPS = b'''<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Target="/3D/3dmodel.model" Id="rel0" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/></Relationships>'''

# --orientation choices and the Print_Orientation value each selects.
ORIENTATIONS = {
    "upright": "Upright",
    "front-down": "Front face down",
    "back-down": "Back face down",
}

# Export overrides: CLI spelling, OpenSCAD parameter, help text.
OVERRIDES = {
    "front_text": ("Front_Characters", "front inscription"),
    "back_text": ("Back_Characters", "back inscription"),
    "body_color": ("Body_Filament", "body filament, e.g. Wood"),
    "front_color": ("Front_Filament", "front lettering filament, e.g. Black"),
    "back_color": ("Back_Filament", "back lettering filament, e.g. Red"),
    "signature_text": ("Signature_Text", "heel signature; also enables it"),
    "signature_color": ("Signature_Filament", "signature filament"),
}

# Orthographic preview cameras square onto each face; the distance fixes a shared scale.
PREVIEW_VIEWS = {"front": "0,0,16,90,0,0,120", "back": "0,0,16,90,0,180,120"}
PREVIEW_SIZE = "360,400"


def shown(path):
    """Describe a path relative to the project when it lies inside it."""
    try:
        return path.relative_to(ROOT).as_posix()
    except ValueError:
        return str(path)


def read_json(path):
    """Parse one JSON file, naming it in any error."""
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        raise ValueError("Missing file: %s" % shown(path))
    except json.JSONDecodeError as error:
        raise ValueError("Invalid JSON in %s: %s" % (shown(path), error))


# --- Building game presets from the piece files -----------------------------

def face(source, side, style, where):
    """Return the ``style`` settings of one face, or explain what is missing."""
    styles = source.get(side, {})
    if style not in styles:
        raise ValueError("%s has no %s style %r (available: %s)" % (
            where, side, style, ", ".join(styles) or "none"))
    return styles[style]


def build_preset(defaults, piece, filename, front, back):
    """Layer the shared defaults and one piece into a full parameter set.

    Later layers win: common defaults -> front style defaults -> back style
    defaults -> piece body -> piece front style -> piece back style.
    """
    where = "%s.json" % filename
    layers = [
        defaults["common"],
        face(defaults, "front", front, "_defaults.json"),
        face(defaults, "back", back, "_defaults.json"),
        piece.get("body", {}),
        face(piece, "front", front, where),
    ]
    # Kings and golds have no promoted side: their reverse stays blank.
    if "back" in piece:
        layers.append(face(piece, "back", back, where))
    known = set(layers[0]) | set(layers[1]) | set(layers[2]) | {
        "Piece_Length", "Base_Width", "Rear_Thickness", "Tip_Thickness"}
    preset = {}
    for layer in layers:
        unknown = sorted(set(layer) - known)
        if unknown:
            raise ValueError("%s uses unknown parameter(s): %s" % (where, ", ".join(unknown)))
        preset.update(layer)
    return preset


def build_games():
    """Return ``{game: (presets, counts)}`` for every recipe in games.json.

    ``presets`` maps preset names to parameters; ``counts`` maps the same
    names to how many of that piece a complete set needs.
    """
    defaults = read_json(PIECES / "_defaults.json")
    games = {}
    for key, recipe in read_json(RECIPES).items():
        sets, counts = {}, {}
        for number, (filename, count) in enumerate(recipe["pieces"].items(), 1):
            piece = read_json(PIECES / (filename + ".json"))
            preset = build_preset(defaults, piece, filename, recipe["front"], recipe["back"])
            preset["Category"] = "%s / %s" % (recipe["title"], piece["category"])
            name = "%s %02d - %s" % (recipe["title"], number, piece["name"])
            sets[name], counts[name] = preset, count
        games[key] = (sets, counts)
    return games


def render_presets(sets, counts=None):
    """Serialize parameter sets the way the OpenSCAD Customizer saves them.

    ``counts`` adds the ``pieceCounts`` object the export command reads;
    OpenSCAD ignores it.
    """
    document = {"fileFormatVersion": "1", "parameterSets": sets}
    if counts:
        document["pieceCounts"] = counts
    return json.dumps(document, ensure_ascii=False, indent=4, sort_keys=True) + "\n"


def generated_files(games):
    """Return ``{path: text}`` for every file the build command writes."""
    combined = {}
    for sets, _ in games.values():
        duplicate = sorted(set(sets) & set(combined))
        if duplicate:
            raise ValueError("Two games produce the same preset name: " + duplicate[0])
        combined.update(sets)
    outputs = {GAMES / (key + ".json"): render_presets(sets, counts)
               for key, (sets, counts) in games.items()}
    outputs[CUSTOMIZER] = render_presets(combined)
    return outputs


def stale_files(outputs):
    """List generated files that are missing or differ from a fresh build."""
    return [path for path, text in outputs.items()
            if not path.exists() or path.read_text(encoding="utf-8") != text]


def unsaved_edits():
    """List Customizer changes in shogi_piece.json that a rebuild would erase.

    The Customizer saves into shogi_piece.json, which the build regenerates.
    Anything there that differs from the last build exists nowhere else.
    """
    if not CUSTOMIZER.exists():
        return []
    current = read_json(CUSTOMIZER).get("parameterSets", {})
    previous = {}
    for path in sorted(GAMES.glob("*.json")):
        previous.update(read_json(path).get("parameterSets", {}))
    edits = []
    for name, values in current.items():
        if name not in previous:
            edits.append("%s: preset is not in any game file" % name)
            continue
        for parameter in sorted(set(values) | set(previous[name])):
            old, new = previous[name].get(parameter), values.get(parameter)
            if old != new:
                edits.append("%s: %s = %s (built value: %s)" % (name, parameter, new, old))
    return edits


def cmd_build(args):
    """Rebuild the generated preset files, or report which are out of date."""
    games = build_games()
    outputs = generated_files(games)

    if args.check:
        stale = stale_files(outputs)
        for path in stale:
            print("Out of date: %s" % shown(path))
        return 1 if stale else 0

    edits = [] if args.force else unsaved_edits()
    if edits:
        print("shogi_piece.json has Customizer edits that are not in the piece files:\n")
        for edit in edits:
            print("  " + edit)
        raise ValueError("Copy the values you want to keep into presets/pieces/, "
                         "then rerun (or use --force to discard them).")

    GAMES.mkdir(parents=True, exist_ok=True)
    for path, text in outputs.items():
        path.write_text(text, encoding="utf-8")
    for key, (sets, counts) in games.items():
        print("presets/games/%s.json: %d presets, %d pieces in a full set" % (
            key, len(sets), sum(counts.values())))
    print("shogi_piece.json: %d presets (all games, for the Customizer)" % sum(
        len(sets) for sets, _ in games.values()))
    return 0


# --- Reading preset files ---------------------------------------------------

def find_preset_file(text):
    """Resolve a GAME argument: a game name, or a path to any preset JSON."""
    path = Path(text)
    if not path.is_file():
        path = GAMES / (text + ".json")
    if not path.is_file():
        games = sorted(candidate.stem for candidate in GAMES.glob("*.json"))
        close = difflib.get_close_matches(text, games, 1)
        raise ValueError("No game or preset file named %r.%s Games: %s" % (
            text, " Did you mean %r?" % close[0] if close else "", ", ".join(games)))
    path = path.resolve()
    # shogi_piece.json may hold deliberate Customizer edits, so only the
    # per-game files are held to the piece files.
    if path.parent == GAMES and path in stale_files(generated_files(build_games())):
        raise ValueError("%s is older than the piece files. Run '%s build' first."
                         % (shown(path), Path(sys.argv[0]).name))
    return path


def load_parameter_sets(path):
    """Read a Customizer preset file.

    Returns ``(sets, counts)``: the named parameter sets in file order, and
    how many copies of each a complete set needs. Counts come from an
    optional top-level ``pieceCounts`` object; presets it omits count once.
    """
    document = read_json(path)
    sets = document["parameterSets"]
    declared = document.get("pieceCounts", {})
    return sets, {name: declared.get(name, 1) for name in sets}


def select_presets(names, filters):
    """Pick presets by exact name or case-insensitive part of a name.

    No filters selects everything. The result keeps file order.
    """
    if not filters:
        return list(names)
    chosen = set()
    for text in filters:
        matches = [text] if text in names else [
            name for name in names if text.casefold() in name.casefold()]
        if not matches:
            raise ValueError("No piece matches %r. Use the list command to see the names." % text)
        chosen.update(matches)
    return [name for name in names if name in chosen]


def cmd_list(args):
    """Show every game, or the presets inside one game or preset file."""
    if args.game is None:
        rows = [("GAME", "PIECES", "FULL SET")] + [
            (key, str(len(sets)), str(sum(counts.values())))
            for key, (sets, counts) in build_games().items()]
        width = max(len(row[0]) for row in rows)
        for game, pieces, total in rows:
            print("%s  %6s  %8s" % (game.ljust(width), pieces, total))
        return 0
    sets, counts = load_parameter_sets(find_preset_file(args.game))
    for name, values in sets.items():
        line = name if counts[name] == 1 else "%s  x%d" % (name, counts[name])
        if args.long:
            line += "  [%s]" % values.get("Category", "no category")
        print(line)
    return 0


# --- Editing hand-kept preset files -----------------------------------------

def assignment(text):
    """Parse one ``NAME=VALUE`` argument, keeping the value as text."""
    key, separator, value = text.partition("=")
    if not separator:
        raise argparse.ArgumentTypeError("use NAME=VALUE, for example Base_Width=30")
    return key.strip(), value


def cmd_set(args):
    """Apply the same parameter values to a chosen group of presets."""
    path = args.file.resolve()
    document = read_json(path)
    sets = document["parameterSets"]
    names = [text.casefold() for text in args.preset]
    categories = [text.casefold() for text in args.category]
    changes = []
    selected = 0
    for name, values in sets.items():
        category = str(values.get("Category", "")).casefold()
        if not (args.all or any(text in name.casefold() for text in names)
                or any(text in category for text in categories)):
            continue
        selected += 1
        for key, value in args.assignments:
            if key not in values:
                raise ValueError("%r has no parameter %r; check the spelling" % (name, key))
            old = values[key]
            if old != value:
                changes.append("%s: %s: %r -> %r" % (name, key, old, value))
                values[key] = value
    for change in changes:
        print(change)
    if args.dry_run:
        print("Would change %d value(s) in %d selected preset(s); nothing written." % (len(changes), selected))
    elif changes:
        path.write_text(json.dumps(document, ensure_ascii=False, indent=4) + "\n", encoding="utf-8")
        print("Changed %d value(s) in %d selected preset(s) of %s." % (len(changes), selected, shown(path)))
    else:
        print("Nothing to change in %d selected preset(s)." % selected)
    return 0


# --- Running OpenSCAD -------------------------------------------------------

def run_openscad(command):
    """Run OpenSCAD headlessly and return ``(exit status, combined output)``."""
    environment = os.environ.copy()
    if sys.platform.startswith("linux") and not environment.get("DISPLAY"):
        environment.setdefault("QT_QPA_PLATFORM", "offscreen")
    result = subprocess.run(command, capture_output=True, text=True, env=environment)
    return result.returncode, result.stdout + "\n" + result.stderr


@functools.lru_cache(maxsize=None)
def scad_parameters(scad):
    """Return ``(public defaults, hidden names)`` declared in the SCAD source."""
    source = scad.read_text(encoding="utf-8")
    public_source, marker, hidden_source = source.partition("/* [Hidden] */")
    defaults = {
        name: json.loads(value)
        for name, value in re.findall(r"^([A-Za-z_]\w*)\s*=\s*(.+?);", public_source, re.M)
    }
    hidden = set(re.findall(r"^([A-Za-z_]\w*)\s*=", hidden_source if marker else "", re.M))
    return defaults, hidden


def scad_definitions(scad, preset, values, overrides):
    """Turn one saved preset plus overrides into OpenSCAD ``-D`` arguments.

    OpenSCAD 2021.01 preset loading can override -D public parameters, so the
    values are read here and passed explicitly: overrides always win.
    """
    defaults, hidden = scad_parameters(scad)
    typed = {}
    for name, value in values.items():
        # OpenSCAD 2021.01 can leak variables declared after its Hidden marker
        # into a saved preset. They are implementation details, so skip them
        # while still rejecting unknown or misspelled public parameters.
        if name in hidden:
            continue
        if name not in defaults:
            raise ValueError("Preset %r has an unsupported parameter: %s" % (preset, name))
        typed[name] = value if isinstance(defaults[name], str) or not isinstance(value, str) \
            else json.loads(value)
    typed.update(overrides)
    definitions = []
    for name, value in typed.items():
        if name != "Output_Mode":
            definitions.extend(["-D", name + "=" + json.dumps(value, ensure_ascii=False)])
    return definitions


def check_fonts(log):
    """Reject substituted font families when fontconfig tools are present."""
    match = re.search(r'^ECHO: "KOMASCAD_FONTS", (.+)$', log, re.M)
    if not match or not (shutil.which("fc-match") and shutil.which("fc-pattern")):
        return

    generic_families = {"sans", "sans-serif", "serif", "monospace", "system-ui"}
    # OpenSCAD echoes a literal backslash in some registered font family names
    # (for example ``A\-OTF``), while JSON requires that backslash to be
    # escaped. Preserve OpenSCAD's text and make only those literal slashes
    # JSON-safe before decoding the simple string array.
    encoded_fonts = re.sub(r'\\(?!["\\])', r'\\\\', match.group(1))
    for requested in set(json.loads(encoded_fonts)):
        wanted = subprocess.check_output(
            ["fc-pattern", "-f", "%{family}", requested], text=True,
        ).strip()
        actual = subprocess.check_output(
            ["fc-match", "-f", "%{family}", requested], text=True,
        ).strip()
        wanted_families = {family.strip().casefold() for family in wanted.split(",")}
        actual_families = {family.strip().casefold() for family in actual.split(",")}
        if not (wanted_families & actual_families or wanted_families & generic_families):
            raise ValueError(
                'Font "' + requested + '" resolves to "' + actual + '". '
                "Install the intended font or choose its registered family "
                "in your preset before exporting."
            )


def read_stl(path):
    """Read one binary STL and confirm it is a closed mesh.

    Shared coordinates become shared vertex IDs. Each edge must appear in two
    triangles with opposite directions. If independently closed glyph shells
    merely touch along an edge, their vertex IDs are separated without moving
    coordinates; this preserves the exact outline while keeping each shell
    topologically manifold.

    Returns ``(vertices, faces)``: XYZ tuples and triples of vertex indices.
    """
    data = path.read_bytes()
    triangle_count = struct.unpack_from("<I", data, 80)[0]

    vertices = []
    faces = []
    vertex_ids = {}
    for triangle_index in range(triangle_count):
        # A binary triangle stores its normal, three vertices, and two spare bytes.
        values = struct.unpack_from("<12fH", data, 84 + 50 * triangle_index)
        face = []
        for start in (3, 6, 9):
            xyz = tuple(values[start:start + 3])
            if xyz not in vertex_ids:
                vertex_ids[xyz] = len(vertices)
                vertices.append(xyz)
            face.append(vertex_ids[xyz])
        faces.append(face)

    def edge_statistics(mesh_faces):
        statistics = {}
        for a, b, c in mesh_faces:
            for start, end in ((a, b), (b, c), (c, a)):
                edge = (min(start, end), max(start, end))
                count, balance = statistics.get(edge, (0, 0))
                statistics[edge] = (
                    count + 1, balance + (1 if start < end else -1),
                )
        return statistics

    edges = edge_statistics(faces)
    if any(count != 2 or balance != 0 for count, balance in edges.values()):
        # Font outlines can form separate closed extrusions that touch at an
        # exact edge. STL has coordinates but no vertex topology, so global
        # coordinate deduplication makes that edge appear four-sided. Discover
        # shells through ordinary two-face edges, then give touching shells
        # independent IDs at the same coordinates. Truly open or inconsistently
        # wound input still fails the closure check below.
        edge_faces = {}
        face_edges = []
        for face_index, (a, b, c) in enumerate(faces):
            local_edges = []
            for start, end in ((a, b), (b, c), (c, a)):
                edge = (min(start, end), max(start, end))
                edge_faces.setdefault(edge, []).append(face_index)
                local_edges.append(edge)
            face_edges.append(local_edges)

        components = [-1] * len(faces)
        component = 0
        for seed in range(len(faces)):
            if components[seed] != -1:
                continue
            components[seed] = component
            pending = [seed]
            while pending:
                face_index = pending.pop()
                for edge in face_edges[face_index]:
                    incident = edge_faces[edge]
                    if len(incident) != 2:
                        continue
                    other = incident[0] if incident[1] == face_index else incident[1]
                    if components[other] == -1:
                        components[other] = component
                        pending.append(other)
            component += 1

        separated_vertices = []
        separated_faces = []
        separated_ids = {}
        for face_index, face in enumerate(faces):
            separated_face = []
            for vertex_id in face:
                key = (components[face_index], vertex_id)
                if key not in separated_ids:
                    separated_ids[key] = len(separated_vertices)
                    separated_vertices.append(vertices[vertex_id])
                separated_face.append(separated_ids[key])
            separated_faces.append(separated_face)
        vertices, faces = separated_vertices, separated_faces
        edges = edge_statistics(faces)

    if any(count != 2 or balance != 0 for count, balance in edges.values()):
        raise ValueError("Part is not a closed, consistently wound mesh: " + str(path))

    return vertices, faces


def render_parts(executable, scad, definitions):
    """Ask OpenSCAD for every enabled material part of one piece.

    OpenSCAD remains the geometry engine: the meshes are validated and
    packaged, never modified. Returns ``(role, material, rgba, vertices,
    faces)`` tuples in body/front/back/signature order.
    """
    with tempfile.TemporaryDirectory(prefix="komascad-") as temporary:
        folder = Path(temporary)

        # First run: which material parts does this piece have, in which colors?
        echo = folder / "materials.echo"
        status, log = run_openscad(
            [executable, "--hardwarnings", "-o", str(echo)] + definitions
            + ["-D", 'Output_Mode="Color assembly"', "-D", "Export_Metadata=true", str(scad)])
        if echo.exists():
            log += "\n" + echo.read_text(encoding="utf-8")
        if status or "ERROR:" in log or "WARNING:" in log:
            raise RuntimeError("OpenSCAD could not read the piece:\n" + log[-8000:])
        match = re.search(r'^ECHO: "KOMASCAD_EXPORT", (.+)$', log, re.M)
        check_fonts(log)
        enabled = [part[:3] for part in json.loads(match.group(1)) if part[3]]

        # Second run: OpenSCAD animation frames share geometry and CGAL caches,
        # so selecting one output mode per frame renders every part without
        # rebuilding the same piece for body, front, back and signature.
        modes = ["Color " + role for role, _, _ in enabled]
        mode_expression = "%s[min(floor($t*%d),%d)]" % (
            json.dumps(modes, ensure_ascii=False), len(modes), len(modes) - 1)
        output = folder / "part.stl"
        status, log = run_openscad(
            [executable, "--animate", str(len(modes)), "-o", str(output), "--export-format", "binstl"]
            + definitions
            + ["-D", "Output_Mode=" + mode_expression, "-D", "Export_Metadata=false", str(scad)])
        # A direct extrusion can contain independently closed font shells that
        # touch at an exact edge. OpenSCAD warns because STL carries no
        # topology; read_stl() separates their vertex IDs and then performs
        # the strict mesh check. All other OpenSCAD warnings remain fatal.
        allowed = (
            "Object may not be a valid 2-manifold and may need repair",
            "Exported object may not be a valid 2-manifold and may need repair",
        )
        unexpected = [line for line in log.splitlines()
                      if "WARNING:" in line and not any(message in line for message in allowed)]
        if status or "ERROR:" in log or unexpected:
            raise RuntimeError("OpenSCAD could not export color parts:\n" + log[-8000:])

        parts = []
        for index, (role, material, rgba) in enumerate(enabled):
            frame = output.with_name("%s%05d%s" % (output.stem, index, output.suffix))
            parts.append((role, material, rgba) + read_stl(frame))
        return parts


# --- Writing 3MF files ------------------------------------------------------

def node(parent, tag, **attrs):
    """Add an element in the 3MF model namespace."""
    qualified_tag = "{%s}%s" % (MODEL_NAMESPACE, tag)
    return ET.SubElement(parent, qualified_tag, {k: str(v) for k, v in attrs.items()})


def hex_color(rgba):
    """Format the RGB channels of a 0-1 color as ``#RRGGBB``."""
    return "#" + "".join("%02X" % round(255 * channel) for channel in rgba[:3])


def grid_positions(bounds):
    """Place pieces on a regular grid centerd at the origin.

    Args:
        bounds: One ``(min_x, max_x, min_y, max_y)`` footprint per piece.

    Returns:
        The ``(x, y)`` translation for each piece, filling rows left to right
        from the back. A single piece is left where it is.
    """
    if len(bounds) == 1:
        return [(0.0, 0.0)]
    # A shared cell size keeps the grid regular and guarantees no overlap.
    # The extra margin makes individual pieces easy to click in a slicer.
    margin = 6.0
    cell_width = max(max_x - min_x for min_x, max_x, _, _ in bounds) + margin
    cell_depth = max(max_y - min_y for _, _, min_y, max_y in bounds) + margin
    columns = math.ceil(math.sqrt(len(bounds)))
    rows = math.ceil(len(bounds) / columns)
    positions = []
    for index, (min_x, max_x, min_y, max_y) in enumerate(bounds):
        column, row = index % columns, index // columns
        # Center each piece in its cell, then center the full grid at origin.
        positions.append(((column - (columns - 1) / 2) * cell_width - (min_x + max_x) / 2,
                          ((rows - 1) / 2 - row) * cell_depth - (min_y + max_y) / 2))
    return positions


def create_3mf(destination, pieces, title):
    """Package one or more pieces as a portable multipart color 3MF.

    Every piece is a named object made of aligned material parts. Core
    ``basematerials`` retain human-readable filament names, and one Materials
    and Properties ``colorgroup`` per material gives every mesh an
    object-level color: several FDM slicers treat base materials as display
    only but convert color properties to logical filament assignments. The
    file holds standard geometry and color only, so the slicer stays free to
    choose the printer, filament and process settings.

    Args:
        destination: ``.3mf`` path to write.
        pieces: ``(preset name, parts)`` pairs from ``render_parts``. Repeat
            a pair to place more copies; the copies share one stored mesh but
            are separate named objects. A single piece keeps its coordinates;
            several are spaced on a grid centerd at the origin.
        title: Human-readable model name.

    Returns:
        One ``{"preset", "object_id", "x", "y", "parts"}`` record per placed piece.
    """
    model = ET.Element(
        "{%s}model" % MODEL_NAMESPACE,
        {"unit": "millimeter", "{http://www.w3.org/XML/1998/namespace}lang": "en-US"},
    )
    node(model, "metadata", name="Title").text = title
    node(model, "metadata", name="Application").text = "KomaSCAD " + VERSION
    node(model, "metadata", name="Description").text = (
        "Shogi pieces as separately selectable multipart objects with standard "
        "3MF material and color assignments. Glitter/metallic labels describe "
        "filament choice, not surface textures. No printer, filament, or "
        "slicing settings are embedded."
    )
    resources = node(model, "resources")
    materials = node(resources, "basematerials", id=1)

    # The material key deliberately includes the name: two visually equal
    # swatches may still describe different physical filaments.
    color_groups = {}
    bounds = []
    for preset, parts in pieces:
        xs = [vertex[0] for part in parts for vertex in part[3]]
        ys = [vertex[1] for part in parts for vertex in part[3]]
        bounds.append((min(xs), max(xs), min(ys), max(ys)))
        for _, material, rgba, _, _ in parts:
            key = (material, hex_color(rgba))
            if key not in color_groups:
                color_groups[key] = None
                # Explicit opaque alpha avoids readers that incorrectly
                # interpret a legal six-digit 3MF color as transparent RGBA.
                node(materials, "base", name=material, displaycolor=key[1] + "FF")

    # Separate one-color groups retain compatibility with consumers that do
    # not implement pindex fully.
    next_resource_id = 2
    for key in color_groups:
        color_groups[key] = next_resource_id
        group = ET.SubElement(resources, "{%s}colorgroup" % MATERIAL_NAMESPACE,
                              {"id": str(next_resource_id)})
        ET.SubElement(group, "{%s}color" % MATERIAL_NAMESPACE, {"color": key[1] + "FF"})
        next_resource_id += 1

    build = node(model, "build")
    placed = []
    mesh_ids = {}

    for (preset, parts), (shift_x, shift_y) in zip(pieces, grid_positions(bounds)):
        # A repeated preset reuses the meshes written for its first copy.
        if preset not in mesh_ids:
            mesh_ids[preset] = []
            for role, material, rgba, vertices, faces in parts:
                mesh_ids[preset].append(next_resource_id)
                part_object = node(
                    resources, "object", id=next_resource_id, type="model",
                    name=role.title() + " | " + material,
                    pid=color_groups[(material, hex_color(rgba))], pindex=0,
                )
                next_resource_id += 1
                mesh = node(part_object, "mesh")
                xml_vertices = node(mesh, "vertices")
                xml_faces = node(mesh, "triangles")
                for x, y, z in vertices:
                    node(xml_vertices, "vertex", x=format(x, ".9g"), y=format(y, ".9g"), z=format(z, ".9g"))
                for a, b, c in faces:
                    node(xml_faces, "triangle", v1=a, v2=b, v3=c)

        # Every copy gets its own named object. Bambu Studio turns build items
        # that share one object into unnamed duplicates.
        assembly_id = next_resource_id
        next_resource_id += 1
        assembly = node(resources, "object", id=assembly_id, type="model", name=preset)
        components = node(assembly, "components")
        for object_id in mesh_ids[preset]:
            node(components, "component", objectid=object_id)

        if len(pieces) == 1:
            node(build, "item", objectid=assembly_id)
        else:
            transform = "1 0 0 0 1 0 0 0 1 %s %s 0" % (format(shift_x, ".9g"), format(shift_y, ".9g"))
            node(build, "item", objectid=assembly_id, transform=transform)
        placed.append({
            "preset": preset, "object_id": assembly_id, "x": shift_x, "y": shift_y,
            "parts": [{"part": role, "material": material, "display_color": hex_color(rgba)}
                      for role, material, rgba, _, _ in parts],
        })

    with zipfile.ZipFile(destination, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("[Content_Types].xml", CONTENT_TYPES)
        archive.writestr("_rels/.rels", RELATIONSHIPS)
        archive.writestr("3D/3dmodel.model", ET.tostring(model, encoding="utf-8", xml_declaration=True))
        archive.writestr("Metadata/KomaSCAD.json", json.dumps({
            "version": VERSION, "units": "mm", "pieces": placed,
            "type": "portable multipart model with standard color assignments; no printer settings",
        }, ensure_ascii=False, indent=2))
    return placed


# --- Exporting --------------------------------------------------------------

def per_file(text):
    """Parse ``--per-file``: a positive piece count, or ``all`` for one file."""
    return math.inf if text == "all" else int(text)


def safe_name(name):
    """Convert a preset or set name into a readable cross-platform filename.

    >>> safe_name('Chu Shogi: Lion / Kirin')
    'Chu Shogi - Lion - Kirin'
    """
    cleaned = re.sub(r'[<>:"/\\|?*\x00-\x1f]', " - ", name)
    cleaned = re.sub(r"\s+", " ", cleaned).strip(" .")
    return re.sub(r"(?:\s*-\s*){2,}", " - ", cleaned)


def plan_files(presets, counts, set_name, size):
    """Decide which pieces go into which output file.

    Without ``size`` every preset gets its own file. With it, the full count
    of every preset is split into layout files of at most ``size`` pieces.

    Returns:
        ``(filename, [preset, ...])`` pairs in export order.
    """
    if size:
        # One entry per physical piece, so the layouts hold the full count.
        placements = [preset for preset in presets for _ in range(counts[preset])]
        step = len(placements) if size == math.inf else size
        return [("%s - Layout %02d.3mf" % (safe_name(set_name), number), placements[first:first + step])
                for number, first in enumerate(range(0, len(placements), step), 1)]
    return [(safe_name(preset) + ".3mf", [preset]) for preset in presets]


def describe_pieces(presets):
    """Summarize placed presets for progress output, e.g. ``Pawn x18, King``."""
    counts = {}
    for preset in presets:
        counts[preset] = counts.get(preset, 0) + 1
    return ", ".join(name if count == 1 else "%s x%d" % (name, count) for name, count in counts.items())


def portable_path(path):
    """Describe a source file without revealing where the project is stored.

    Manifests are shared with exported sets, so they must not record a
    maker's home directory or username: files outside the project keep only
    their name.
    """
    try:
        return path.relative_to(ROOT).as_posix()
    except ValueError:
        return path.name


def sha256_file(path):
    """Calculate a SHA-256 checksum without loading a whole 3MF into memory."""
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for block in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def write_manifest(folder, set_name, preset_file, scad, plan, counts, layouts):
    """Record provenance, contents, sizes and checksums of an exported set.

    A layout file lists the presets placed in it; a single-piece file names
    its preset and how many copies a complete set needs.
    """
    files = []
    for filename, members in plan:
        entry = {"file": filename}
        if layouts:
            entry["presets"] = members
        else:
            entry.update(preset=members[0], quantity=counts[members[0]])
        entry.update(bytes=(folder / filename).stat().st_size, sha256=sha256_file(folder / filename))
        files.append(entry)
    document = {
        "format_version": 1,
        "set_name": set_name,
        "source_parameters": portable_path(preset_file),
        "source_scad": portable_path(scad),
        "piece_count": len(counts),
        "total_quantity": sum(counts.values()),
        "files": files,
    }
    (folder / "manifest.json").write_text(
        json.dumps(document, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def cmd_export(args):
    """Export chosen presets of one game or preset file as color 3MF files."""
    preset_file = find_preset_file(args.game)
    scad = args.scad.resolve()
    sets, counts = load_parameter_sets(preset_file)
    selected = select_presets(list(sets), args.piece)

    overrides = {parameter: getattr(args, option) for option, (parameter, _) in OVERRIDES.items()
                 if getattr(args, option) is not None}
    if args.signature_text is not None:
        overrides["Signature_Enabled"] = True
    if args.orientation:
        overrides["Print_Orientation"] = ORIENTATIONS[args.orientation]

    set_name = args.name or preset_file.stem.replace("_", " ").replace("-", " ").title()
    destination = (args.output or Path("exports") / preset_file.stem).resolve()
    plan = plan_files(selected, counts, set_name, args.per_file)

    if args.dry_run:
        print(str(destination) + os.sep)
        for filename, members in plan:
            if args.per_file:
                print("  %s  (%d pieces: %s)" % (filename, len(members), describe_pieces(members)))
            else:
                copies = counts[members[0]]
                print("  " + filename + ("" if copies == 1 else "  (print %d)" % copies))
        return 0

    destination.mkdir(parents=True, exist_ok=True)

    exported = skipped = 0
    rendered = {}
    for index, (filename, members) in enumerate(plan, 1):
        output = destination / filename
        progress = "[%d/%d] " % (index, len(plan))
        if output.exists() and not args.force:
            print(progress + "Skipping existing " + filename, flush=True)
            skipped += 1
            continue
        print(progress + "Exporting " + describe_pieces(members), flush=True)
        # Each preset is rendered once, however many copies are placed.
        for preset in members:
            if preset not in rendered:
                if len(set(members)) > 1:
                    print("      rendering " + preset, flush=True)
                rendered[preset] = render_parts(
                    args.openscad, scad, scad_definitions(scad, preset, sets[preset], overrides))
        # A completed file appears under its final name only once it is
        # whole, so an interrupted export is never mistaken for a finished one.
        partial = output.with_name("." + output.name + ".partial")
        try:
            create_3mf(partial, [(preset, rendered[preset]) for preset in members],
                       members[0] if len(members) == 1 else filename[:-4])
            os.replace(partial, output)
        finally:
            if partial.exists():
                partial.unlink()
        exported += 1

    print("Saved %d new 3MF file(s); skipped %d existing in %s" % (exported, skipped, destination))
    # A manifest describes a complete delivery, so a hand-picked subset has none.
    if not args.piece:
        write_manifest(destination, set_name, preset_file, scad, plan, counts, bool(args.per_file))
        print("Manifest: " + str(destination / "manifest.json"))
        if not args.per_file and any(count > 1 for count in counts.values()):
            print("Some pieces are needed more than once; the manifest lists quantities. "
                  "Use --per-file all for the complete set in one file.")
    return 0


# --- Previewing -------------------------------------------------------------

def cmd_preview(args):
    """Render every piece of a game, front and back, onto one HTML page.

    The Customizer shows one preset at a time; this shows a whole set at one
    scale so it can be checked before exporting.
    """
    preset_file = find_preset_file(args.game)
    names = list(load_parameter_sets(preset_file)[0])
    out = (args.output or Path("exports") / "preview" / preset_file.stem).resolve()
    out.mkdir(parents=True, exist_ok=True)

    def render(job):
        name, view, target = job
        status, log = run_openscad([
            args.openscad, "-o", str(target), "--imgsize=" + PREVIEW_SIZE, "--projection=o",
            "--camera=" + PREVIEW_VIEWS[view], "-p", str(preset_file), "-P", name, str(SCAD)])
        if status or not target.exists():
            return "%s (%s): %s" % (name, view, (log.strip().splitlines() or ["no output"])[-1])
        return None

    jobs = [(name, view, out / ("%02d-%s.png" % (index, view)))
            for index, name in enumerate(names, 1) for view in PREVIEW_VIEWS]
    print("Rendering %d pieces from %s ..." % (len(names), shown(preset_file)), flush=True)
    with ThreadPoolExecutor() as pool:
        errors = [error for error in pool.map(render, jobs) if error]
    if errors:
        raise RuntimeError("Render failed:\n  " + "\n  ".join(errors))

    cells = "".join(
        '<figure><img src="%02d-front.png" alt=""><img src="%02d-back.png" alt="">'
        "<figcaption>%s</figcaption></figure>" % (index, index, html.escape(name))
        for index, name in enumerate(names, 1)
    )
    page = (
        '<!doctype html><meta charset="utf-8"><title>%s</title>'
        "<style>body{font-family:sans-serif;margin:16px;background:#fffde7}"
        "main{display:flex;flex-wrap:wrap;gap:8px}figure{margin:0;text-align:center}"
        "img{display:block;width:180px}figcaption{font-size:13px;padding:4px}</style>"
        "<h1>%s</h1><p>Front above, back below. All pieces share one scale.</p><main>%s</main>"
    ) % (html.escape(preset_file.stem), html.escape(preset_file.stem), cells)
    index = out / "index.html"
    index.write_text(page, encoding="utf-8")
    print("Preview: " + str(index))
    return 0


# --- Command line -----------------------------------------------------------

def build_parser():
    """Define every command, its options and its help text in one place."""
    parser = argparse.ArgumentParser(
        description="Build, preview and export 3D-printable shogi pieces.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""\
A GAME is a game name (see '%(prog)s list') or a path to any preset JSON file.

examples:
  %(prog)s list                           show the games
  %(prog)s export shogi --per-file all    the complete set in one color 3MF
  %(prog)s export shogi pawn              just the pawn
  %(prog)s preview minishogi              check a whole set on one page
  %(prog)s build                          after editing presets/pieces/

Run '%(prog)s COMMAND --help' for the options of one command.
""")
    parser.add_argument("-V", "--version", action="version", version="KomaSCAD " + VERSION)
    commands = parser.add_subparsers(dest="command", metavar="COMMAND", title="commands")

    def command(name, run, summary, examples, **options):
        result = commands.add_parser(
            name, help=summary, description=summary[0].upper() + summary[1:] + ".",
            formatter_class=argparse.RawDescriptionHelpFormatter,
            epilog="examples:\n" + examples, **options)
        result.set_defaults(run=run)
        return result

    listing = command("list", cmd_list, "show the games, or the pieces in one game", """\
  %(prog)s            every game and its size
  %(prog)s shogi      the pieces in shogi, with how many a set needs
  %(prog)s -l presets/misc/taikyoku.json
""")
    listing.add_argument("game", nargs="?", metavar="GAME", help="game name or preset JSON file")
    listing.add_argument("-l", "--long", action="store_true", help="also show each piece's category")

    build = command("build", cmd_build, "rebuild the game presets from presets/pieces/", """\
  %(prog)s            rebuild presets/games/ and shogi_piece.json
  %(prog)s --check    exit 1 if they are out of date; write nothing
""")
    build.add_argument("--check", action="store_true",
                       help="exit 1 if any generated file is out of date; write nothing")
    build.add_argument("-f", "--force", action="store_true",
                       help="overwrite shogi_piece.json even if it holds unsaved Customizer edits")

    preview = command("preview", cmd_preview, "render every piece of a game onto one HTML page", """\
  %(prog)s minishogi
  %(prog)s shogi -o /tmp/shogi-preview
""")
    preview.add_argument("game", metavar="GAME", help="game name or preset JSON file")
    preview.add_argument("-o", "--output", type=Path, metavar="DIR",
                         help="output folder (default: exports/preview/GAME)")
    preview.add_argument("--openscad", default="openscad", metavar="PATH", help="OpenSCAD executable")

    export = command("export", cmd_export, "write print-ready color 3MF files", """\
  %(prog)s shogi                        one 3MF per different piece
  %(prog)s shogi --per-file all         the complete 40-piece set in one 3MF
  %(prog)s shogi --per-file 20          the complete set, 20 pieces per 3MF
  %(prog)s shogi pawn king              only the pieces whose names match
  %(prog)s shogi --orientation front-down -o flat
  %(prog)s shogi -n                     show what would be written

Existing files are skipped, so an interrupted export resumes where it
stopped; use --force to write them again.
""")
    export.add_argument("game", metavar="GAME", help="game name or preset JSON file")
    export.add_argument("piece", nargs="*", metavar="PIECE",
                        help="export only pieces whose name is, or contains, this text (default: all)")
    export.add_argument("-o", "--output", type=Path, metavar="DIR",
                        help="folder receiving the 3MF files (default: exports/GAME)")
    export.add_argument("--per-file", type=per_file, metavar="N|all",
                        help="place this many pieces in each 3MF, or 'all' for one file, with as many "
                             "copies of each piece as a complete set needs")
    export.add_argument("--orientation", choices=sorted(ORIENTATIONS),
                        help="how the pieces sit on the bed, overriding the presets: upright stands "
                             "on the heel; front-down and back-down lie flat on that face")
    export.add_argument("-f", "--force", action="store_true",
                        help="overwrite existing 3MF files instead of skipping them")
    export.add_argument("-n", "--dry-run", action="store_true",
                        help="show the files that would be written, without rendering")
    export.add_argument("--name", help="set name used in layout filenames and manifest.json")
    export.add_argument("--scad", type=Path, default=SCAD, metavar="FILE",
                        help="SCAD model to render (default: the bundled shogi_piece.scad)")
    export.add_argument("--openscad", default="openscad", metavar="PATH", help="OpenSCAD executable")
    overrides = export.add_argument_group("overrides for the exported pieces")
    for option, (_, description) in OVERRIDES.items():
        overrides.add_argument("--" + option.replace("_", "-"), metavar="TEXT", help=description)

    setter = command("set", cmd_set, "change a setting across many presets in a hand-kept file", """\
  %(prog)s my.json Base_Width=30 --category 'grid search'
  %(prog)s my.json Front_Relief_Depth=0.30 Back_Relief_Depth=0.30 --all
  %(prog)s my.json 'Front_Glyph_Width=[1.0, 1.1, 1.0]' --preset 'Grid 05' -n

Names are exact Customizer parameter names with underscores. Quote a value
that contains brackets, commas or spaces. For the bundled games, edit
presets/pieces/ and run build instead.
""")
    setter.add_argument("file", type=Path, metavar="FILE", help="Customizer preset JSON file to edit")
    setter.add_argument("assignments", nargs="+", type=assignment, metavar="NAME=VALUE",
                        help="parameter and its new value")
    setter.add_argument("--preset", action="append", default=[], metavar="TEXT",
                        help="select presets whose name contains TEXT; may be repeated")
    setter.add_argument("--category", action="append", default=[], metavar="TEXT",
                        help="select presets whose Category contains TEXT; may be repeated")
    setter.add_argument("--all", action="store_true", help="select every preset in the file")
    setter.add_argument("-n", "--dry-run", action="store_true",
                        help="show the changes without writing the file")
    return parser


def main(argv=None):
    """Run one command; return the process exit status."""
    parser = build_parser()
    args = parser.parse_args(argv)
    if not args.command:
        parser.print_help()
        return 1
    try:
        return args.run(args)
    except (OSError, ValueError, RuntimeError) as error:
        print("%s: error: %s" % (parser.prog, error), file=sys.stderr)
        return 1
    except KeyboardInterrupt:
        return 130


if __name__ == "__main__":
    sys.exit(main())
